# Generated by Django 4.2.3 on 2023-08-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0002_product_cart_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_cart',
            options={'verbose_name_plural': 'product_cart'},
        ),
        migrations.AlterField(
            model_name='product_cart',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
