# Generated by Django 4.2.3 on 2023-08-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0003_alter_product_cart_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_cart',
            name='date_added',
        ),
    ]
