# Generated by Django 4.2.3 on 2023-08-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_date_updated'),
        ('orders', '0003_order_customer_order_delivery_order_product_cart'),
        ('product_cart', '0004_remove_product_cart_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Cart',
            new_name='ProductCart',
        ),
        migrations.AlterModelOptions(
            name='productcart',
            options={},
        ),
    ]
