# Generated by Django 4.2.3 on 2023-08-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_updated',
        ),
    ]
